{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kubemind.fullname" . }}-redis
  labels:
    {{- include "kubemind.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "kubemind.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubemind.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "kubemind.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image | quote }}
          ports:
            - name: tcp-redis
              containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.redis.persistence.storageClass }}
        storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubemind.fullname" . }}-redis
  labels:
    {{- include "kubemind.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: tcp-redis
  selector:
    {{- include "kubemind.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end -}}
