apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubemind.fullname" . }}-secrets
  labels:
    {{- include "kubemind.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ .Values.env.secretKey | quote }}
